# Generated by Django 5.0.4 on 2024-04-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='car_name',
        ),
    ]
