# Generated by Django 5.0.4 on 2024-04-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='top_seller',
            field=models.IntegerField(default=0),
        ),
    ]
