# Generated by Django 5.0.4 on 2024-04-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
