# Generated by Django 5.0.4 on 2024-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_car_description_car_engine_car_fuel_car_transmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_efficiency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(default=0),
        ),
    ]
