# Generated by Django 5.0.4 on 2024-04-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_car_fuel_efficiency_car_horsepower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
