# Generated by Django 5.0.4 on 2024-04-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_car_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
