# Generated by Django 5.0.4 on 2024-04-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_car_engine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(default='', max_length=15),
        ),
    ]
