# Generated by Django 5.0.4 on 2024-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./img/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./img/'),
        ),
    ]
