# Generated by Django 5.0.4 on 2024-04-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_car_image2_car_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./'),
        ),
    ]
