# Generated by Django 5.0.4 on 2024-04-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_car_image_alter_car_image2_alter_car_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(default='', max_length=15),
        ),
    ]
