# Generated by Django 5.0.4 on 2024-05-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
