# Generated by Django 5.0.4 on 2025-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='car_images/'),
        ),
    ]
